baseURL = "https://360solidaires.solidairesinformatique.org/"
DefaultContentLanguage = "fr"
enableEmoji = true
enableRobotsTXT = true
languageCode = "fr-fr"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "360Solidaires"

[module.hugoVersion]
extended = true
min = "0.143.1"

[Params]
comments = false
commit = true
dateFormat = "02/01/2006"
delayDisqus = false
description = "Section Syndicale Solidaires Informatique à 360Learning"
disableMath = true
favicon = "img/logo_solidaires_carre.svg"
mainSections = ["posts"]
menu_item_separator = " · "
readingTime = false
rss = true
selfHosted = true
showRelatedPosts = false
SidebarRecentLimit = 5
socialShare = false
subtitle = "Section Syndicale 360Learning"
useHLJS = false
wordCount = false
  [Params.author]
    name = "360Solidaires"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[[menu.main]]
name = "Actualités"
url = "./"
weight = 1

[[menu.main]]
name = "Vos droits"
weight = 3
url = "page/vos_droits"

[[menu.main]]
name = "S'engager"
weight = 4
url = "page/s_engager"

[[menu.main]]
name = "Notre Programme"
weight = 5
url = "page/programme"

#[[menu.main]]
#name = "F.A.Q."
#weight = 7
#url = "page/faq"

[[menu.main]]
name = "Contact"
weight = 9
url = "page/contact"


[markup.goldmark.renderer]
unsafe= true
